Upload documents from .csv, list-all-data-bundles, metadata
LucidtechAI/las-cli pull request #57
Opened 2022-02-16 14:29 UTC by magnurud

- Add metadata for documents
- add possibility for listing all databundles for all models
- add csv support for uploading a batch of documents
- update version and changelog

2022-02-16 14:36 UTC, augustak requested changes

2022-02-16 14:36 UTC, augustak commented on lascli/parser/models.py
> +        return las_client.list_data_bundles(model['modelId'], max_results=max_results, next_token=next_token)
Is it intended that we are returning on first iteration? Maybe `yield from` was intended here?

2022-02-16 14:38 UTC, augustak commented on lascli/parser/models.py
> +    list_all_data_bundles_parser.add_argument('--next-token', '-n', type=str, default=None)
Do we want to support `--next-token` and `--max-results` when listing **all** data bundles?

2022-02-21 12:01 UTC, augustak requested changes

2022-02-21 12:01 UTC, augustak commented on lascli/parser/models.py
> +        '-p',
Should this be `type=path_to_json` as well?

2022-02-21 13:35 UTC, magnurud commented on CHANGELOG.md
> +
it never existed

2022-02-22 09:43 UTC, augustak requested changes

2022-02-22 09:43 UTC, augustak commented on tests/util.py
> +
Add missing new lines

2022-02-23 09:43 UTC, augustak approved these changes

2022-02-23 10:02 UTC, merged